[phases.setup]
nixPkgs = ["nodejs_18", "npm", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
  "npm --version",
  "node --version", 
  "npm ci"
]

[phases.build]
cmds = [
  "python3 --version",
  "pip3 install -r requirements.txt"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
