name: AlpacaBot CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Node.js dependencies
      run: |
        npm install
        cd client && npm install && cd ..
        cd server && npm install && cd ..

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint JavaScript/TypeScript
      run: |
        cd client && npm run lint || echo "Lint not configured, skipping"

    - name: Lint Python
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test Node.js components
      run: |
        cd client && npm test -- --coverage --watchAll=false || echo "Tests not configured, skipping"
        cd server && npm test || echo "Tests not configured, skipping"

    - name: Test Python components
      run: |
        python -m pytest --version || pip install pytest
        python -m pytest || echo "Tests not configured, skipping"

    - name: Build React app
      run: |
        cd client && npm run build

    - name: Test health endpoint
      run: |
        cd server && timeout 30s node index.js &
        sleep 5
        curl -f http://localhost:3001/health || echo "Health check test failed"

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run security audit
      run: |
        npm audit --audit-level moderate || echo "Security issues found, please review"
        cd client && npm audit --audit-level moderate || echo "Client security issues found"
        cd server && npm audit --audit-level moderate || echo "Server security issues found"

    - name: Check for secrets
      run: |
        if grep -r "ALPACA_API_KEY\|ALPACA_SECRET_KEY" --exclude-dir=.git --exclude="*.md" --exclude=".env.example" .; then
          echo "❌ Potential secrets found in code!"
          exit 1
        else
          echo "✅ No secrets found in code"
        fi

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3

    - name: Test Docker build
      run: |
        if [ -f Dockerfile ]; then
          docker build -t alpacabot:test .
          echo "✅ Docker build successful"
        else
          echo "ℹ️ No Dockerfile found, skipping Docker build"
        fi

  deploy-railway:
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3

    - name: Create Railway deployment package
      run: |
        chmod +x package-for-railway.sh
        ./package-for-railway.sh

    - name: Archive Railway package
      uses: actions/upload-artifact@v3
      with:
        name: railway-deployment-package
        path: /tmp/alpacabot-railway-*.tar.gz
        retention-days: 30

    - name: Comment on PR with deployment info
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚂 **Railway Deployment Ready!**
            
            Your AlpacaBot is ready for Railway deployment:
            1. Download the Railway package from this workflow's artifacts
            2. Extract and push to your Railway repository
            3. Deploy to Railway for FREE 24/7 operation!
            
            📖 See [RAILWAY_QUICK_START.md](RAILWAY_QUICK_START.md) for deployment instructions.`
          })

  release:
    runs-on: ubuntu-latest
    needs: [test, security]
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v3

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: AlpacaBot ${{ github.ref }}
        body: |
          ## 🤖 AlpacaBot Release ${{ github.ref }}
          
          ### 🚀 Quick Deployment
          - **Railway.app**: Deploy for FREE with the Railway package
          - **Desktop**: Download and run locally with Electron
          - **Cloud**: Deploy to AWS, Oracle Cloud, or other providers
          
          ### 📦 Deployment Packages
          - Railway.app deployment package included
          - Docker images available
          - Desktop applications for macOS/Windows/Linux
          
          ### 📚 Documentation
          - [Railway Quick Start](RAILWAY_QUICK_START.md)
          - [Full Deployment Guide](RAILWAY_DEPLOYMENT_GUIDE.md)
          - [Trading System Guide](TRADING_SYSTEM_GUIDE.md)
          
          **⚠️ Risk Disclaimer:** Trading involves substantial risk. Use only with money you can afford to lose.
        draft: false
        prerelease: false
